[package]
name = "ssb-tfk"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
licence = "AGPL-3.0"
edition = "2018"

[features]
default = []
multiformats = ["ssb-multiformats"]

[dependencies]
snafu = "0.6.9"
ssb-multiformats = { version = "0.3.0", optional = true }
